apiVersion: v1
kind: Namespace
metadata:
  name: nginx-testping
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-testping
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-testping
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
